from fastapi.testclient import TestClient
import pytest

from app.agents.query_agent import (
    QueryAgentLowConfidenceError,
    QueryAgentResponseError,
    QueryAgentResult,
    build_openai_messages,
    generate_sql,
    parse_query_agent_response,
)
from app.config import ConfigurationError, get_settings
from app.main import app
from app.modules.api_contract import DestructiveIntentError, validate_safe_question_intent


@pytest.fixture(autouse=True)
def default_query_agent_mode(monkeypatch):
    get_settings.cache_clear()
    monkeypatch.setenv("QUERY_AGENT_MODE", "mock")
    yield
    get_settings.cache_clear()


def test_query_agent_returns_sql_for_all_modules() -> None:
    expected_sql_fragments = {
        "pax_forecast": "JOIN pax_route_targets",
        "special_cruise_profit": "FROM special_cruise_profit",
        "qa": "FROM qa",
    }

    for module_id, expected_fragment in expected_sql_fragments.items():
        result = generate_sql(module_id, "Show sample rows")

        assert expected_fragment in result.sql
        assert result.explanation
        assert result.confidence == "high"
        assert result.assumptions == []


def test_query_agent_populates_schema_context() -> None:
    result = generate_sql("pax_forecast", "Show sample rows")

    assert "Module: Pax Forecast" in result.schema_context_used
    assert "pax_forecast" in result.schema_context_used
    assert "pax_route_targets" in result.schema_context_used


def test_api_ask_uses_query_agent(monkeypatch) -> None:
    from app.config import Settings

    def fake_generate_sql(module_id: str, question: str) -> QueryAgentResult:
        return QueryAgentResult(
            sql="SELECT * FROM qa LIMIT 1",
            explanation="Generated by test Query Agent.",
            confidence="high",
            assumptions=[],
            schema_context_used="test schema context",
        )

    monkeypatch.setattr("app.modules.api_contract.generate_sql", fake_generate_sql)
    monkeypatch.setattr(
        "app.modules.api_contract.refresh_settings",
        lambda: Settings(query_agent_mode="mock"),
    )

    client = TestClient(app)
    response = client.post(
        "/api/ask",
        json={"module_id": "qa", "question": "Show one row"},
    )

    assert response.status_code == 200
    payload = response.json()
    assert payload["sql"] == "SELECT * FROM qa LIMIT 1"
    assert payload["explanation"] == "Generated by test Query Agent."
    assert payload["query_agent_mode"] == "mock"
    assert len(payload["data"]) == 1


def test_api_ask_query_agent_mode_uses_request_time_settings(monkeypatch) -> None:
    from app.config import Settings

    def fake_generate_sql(module_id: str, question: str) -> QueryAgentResult:
        return QueryAgentResult(
            sql="SELECT * FROM qa LIMIT 1",
            explanation="Generated by test Query Agent.",
            confidence="high",
            assumptions=[],
            schema_context_used="test schema context",
        )

    monkeypatch.setattr("app.modules.api_contract.generate_sql", fake_generate_sql)
    monkeypatch.setattr(
        "app.modules.api_contract.refresh_settings",
        lambda: Settings(query_agent_mode="openai", openai_api_key="test-key"),
    )

    client = TestClient(app)
    response = client.post(
        "/api/ask",
        json={"module_id": "qa", "question": "Show one row"},
    )

    assert response.status_code == 200
    assert response.json()["query_agent_mode"] == "openai"


def test_destructive_intent_guard_blocks_question() -> None:
    with pytest.raises(DestructiveIntentError, match="delete"):
        validate_safe_question_intent("Please delete old QA rows")


def test_api_ask_blocks_destructive_intent_before_query_agent(monkeypatch) -> None:
    def fail_if_called(module_id: str, question: str) -> QueryAgentResult:
        raise AssertionError("Query Agent should not be called for destructive intent.")

    monkeypatch.setattr("app.modules.api_contract.generate_sql", fail_if_called)

    client = TestClient(app)
    response = client.post(
        "/api/ask",
        json={"module_id": "qa", "question": "Drop the qa table"},
    )

    assert response.status_code == 400
    assert "Destructive or modifying requests are not allowed" in response.json()["detail"]


def test_validator_still_protects_execution_after_query_agent(monkeypatch) -> None:
    def fake_generate_sql(module_id: str, question: str) -> QueryAgentResult:
        return QueryAgentResult(
            sql="DROP TABLE qa",
            explanation="Unsafe SQL generated by test Query Agent.",
            confidence="low",
            assumptions=["Testing validator protection."],
            schema_context_used="test schema context",
        )

    monkeypatch.setattr("app.modules.api_contract.generate_sql", fake_generate_sql)

    client = TestClient(app)
    response = client.post(
        "/api/ask",
        json={"module_id": "qa", "question": "Show one row"},
    )

    assert response.status_code == 400
    assert "DROP statements are not allowed" in response.json()["detail"]


def test_valid_query_agent_json_response_parses() -> None:
    result = parse_query_agent_response(
        """
        {
          "sql": "SELECT * FROM qa LIMIT 10",
          "explanation": "Returns sample QA rows.",
          "confidence": "high",
          "assumptions": ["The user wants a sample."]
        }
        """,
        schema_context_used="schema context",
    )

    assert result.sql == "SELECT * FROM qa LIMIT 10"
    assert result.explanation == "Returns sample QA rows."
    assert result.confidence == "high"
    assert result.assumptions == ["The user wants a sample."]
    assert result.schema_context_used == "schema context"


def test_malformed_query_agent_json_response_fails() -> None:
    with pytest.raises(QueryAgentResponseError, match="not valid JSON"):
        parse_query_agent_response("{bad json")


def test_query_agent_response_missing_sql_fails() -> None:
    with pytest.raises(QueryAgentResponseError, match="field 'sql' must be a string"):
        parse_query_agent_response(
            """
            {
              "explanation": "Missing SQL.",
              "confidence": "low",
              "assumptions": []
            }
            """
        )


def test_openai_mode_uses_mocked_openai_response(monkeypatch) -> None:
    get_settings.cache_clear()
    monkeypatch.setenv("QUERY_AGENT_MODE", "openai")
    monkeypatch.setenv("OPENAI_API_KEY", "test-key")
    monkeypatch.setenv("OPENAI_MODEL", "gpt-4.1-mini")

    captured_messages: list[dict[str, str]] = []

    def fake_create_chat_completion(messages: list[dict[str, str]]) -> str:
        captured_messages.extend(messages)
        return """
        {
          "sql": "SELECT * FROM qa LIMIT 10",
          "explanation": "Returns QA rows.",
          "confidence": "high",
          "assumptions": []
        }
        """

    monkeypatch.setattr(
        "app.agents.query_agent.openai_client.create_chat_completion",
        fake_create_chat_completion,
    )

    result = generate_sql("qa", "Show QA rows")

    assert result.sql == "SELECT * FROM qa LIMIT 10"
    assert result.confidence == "high"
    assert result.schema_context_used
    assert "read_parquet" not in captured_messages[1]["content"]
    assert "on_time_departure_rate" in captured_messages[1]["content"]

    get_settings.cache_clear()


def test_openai_mode_missing_api_key_fails(monkeypatch) -> None:
    get_settings.cache_clear()
    monkeypatch.setenv("QUERY_AGENT_MODE", "openai")
    monkeypatch.delenv("OPENAI_API_KEY", raising=False)

    with pytest.raises(ConfigurationError, match="OPENAI_API_KEY is required"):
        generate_sql("qa", "Show QA rows")

    get_settings.cache_clear()


def test_openai_low_confidence_response_fails(monkeypatch) -> None:
    get_settings.cache_clear()
    monkeypatch.setenv("QUERY_AGENT_MODE", "openai")
    monkeypatch.setenv("OPENAI_API_KEY", "test-key")

    def fake_create_chat_completion(messages: list[dict[str, str]]) -> str:
        return """
        {
          "sql": "SELECT * FROM qa LIMIT 10",
          "explanation": "Low confidence query.",
          "confidence": "low",
          "assumptions": ["Insufficient metadata."]
        }
        """

    monkeypatch.setattr(
        "app.agents.query_agent.openai_client.create_chat_completion",
        fake_create_chat_completion,
    )

    with pytest.raises(QueryAgentLowConfidenceError, match="low confidence"):
        generate_sql("qa", "Show QA rows")

    get_settings.cache_clear()


def test_openai_messages_include_only_metadata_context() -> None:
    messages = build_openai_messages(
        module_id="qa",
        question="Show QA rows",
        schema_context="Module metadata only",
    )

    assert messages[0]["role"] == "system"
    assert messages[1]["role"] == "user"
    assert "Show QA rows" in messages[1]["content"]
    assert "Module metadata only" in messages[1]["content"]
    assert "read_parquet(" not in messages[1]["content"]
