from fastapi.testclient import TestClient

from app.agents.query_agent import QueryAgentResult, generate_sql
from app.main import app


def test_query_agent_returns_sql_for_all_modules() -> None:
    expected_sql_fragments = {
        "pax_forecast": "JOIN pax_route_targets",
        "special_cruise_profit": "FROM special_cruise_profit",
        "qa": "FROM qa",
    }

    for module_id, expected_fragment in expected_sql_fragments.items():
        result = generate_sql(module_id, "Show sample rows")

        assert expected_fragment in result.sql
        assert result.explanation


def test_query_agent_populates_schema_context() -> None:
    result = generate_sql("pax_forecast", "Show sample rows")

    assert "Module: Pax Forecast" in result.schema_context_used
    assert "pax_forecast" in result.schema_context_used
    assert "pax_route_targets" in result.schema_context_used


def test_api_ask_uses_query_agent(monkeypatch) -> None:
    def fake_generate_sql(module_id: str, question: str) -> QueryAgentResult:
        return QueryAgentResult(
            sql="SELECT * FROM qa LIMIT 1",
            explanation="Generated by test Query Agent.",
            schema_context_used="test schema context",
        )

    monkeypatch.setattr("app.modules.api_contract.generate_sql", fake_generate_sql)

    client = TestClient(app)
    response = client.post(
        "/api/ask",
        json={"module_id": "qa", "question": "Show one row"},
    )

    assert response.status_code == 200
    payload = response.json()
    assert payload["sql"] == "SELECT * FROM qa LIMIT 1"
    assert payload["explanation"] == "Generated by test Query Agent."
    assert len(payload["data"]) == 1


def test_validator_still_protects_execution_after_query_agent(monkeypatch) -> None:
    def fake_generate_sql(module_id: str, question: str) -> QueryAgentResult:
        return QueryAgentResult(
            sql="DROP TABLE qa",
            explanation="Unsafe SQL generated by test Query Agent.",
            schema_context_used="test schema context",
        )

    monkeypatch.setattr("app.modules.api_contract.generate_sql", fake_generate_sql)

    client = TestClient(app)
    response = client.post(
        "/api/ask",
        json={"module_id": "qa", "question": "Drop the table"},
    )

    assert response.status_code == 400
    assert "DROP statements are not allowed" in response.json()["detail"]
